plugins {
    id 'java'
    id 'war'
}

group = 'com.walking.tbooking'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.18.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    implementation 'org.mindrot:jbcrypt:0.4'

    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    implementation 'org.postgresql:postgresql:42.7.2'

    implementation 'com.zaxxer:HikariCP:5.1.0'

    implementation 'org.flywaydb:flyway-core:10.11.0'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql:10.11.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testImplementation 'org.mockito:mockito-core:5.10.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.10.0'

    implementation 'org.apache.logging.log4j:log4j-api:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.12.4'
}

war {
    archiveFileName = 'tbooking.war'
}

test {
    useJUnitPlatform()
}